services:
  - type: web
    name: farmconnect
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: AGMARKNET_API_KEY
        value: 579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b
      - key: GEMINI_API_KEY
        sync: false
